spring:
  main:
    web-application-type: none
    banner-mode: off
  application:
    name: musicplayer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    password: password password
    username: musicplayer
    url: jdbc:h2:~/.musicplayer/db;CIPHER=AES;FILE_LOCK=SOCKET
logging:
  level:
    root: warn
    com.johupe: debug
application:
  ui:
    implicitExit: true
